# Generated by Django 5.2.15 on 2026-06-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0003_perfume_details_admin_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
