# Generated by Django 5.2.15 on 2026-07-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0008_admin_perfume_fields_and_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfume',
            options={'ordering': ['brand', 'name']},
        ),
        migrations.AlterField(
            model_name='perfume',
            name='notes',
            field=models.TextField(blank=True, help_text='Extra description or note details'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='scent_1',
            field=models.CharField(choices=[('citrus', 'Citrus'), ('fresh', 'Fresh'), ('floral', 'Floral'), ('rose', 'Rose'), ('jasmine', 'Jasmine'), ('lavender', 'Lavender'), ('vanilla', 'Vanilla'), ('amber', 'Amber'), ('woody', 'Woody'), ('musk', 'Musk'), ('spicy', 'Spicy'), ('leather', 'Leather'), ('fruity', 'Fruity'), ('aquatic', 'Aquatic'), ('powdery', 'Powdery'), ('sweet', 'Sweet'), ('oriental', 'Oriental'), ('green', 'Green'), ('tobacco', 'Tobacco'), ('oud', 'Oud')], default='floral', max_length=30, verbose_name='Top note'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='scent_2',
            field=models.CharField(choices=[('citrus', 'Citrus'), ('fresh', 'Fresh'), ('floral', 'Floral'), ('rose', 'Rose'), ('jasmine', 'Jasmine'), ('lavender', 'Lavender'), ('vanilla', 'Vanilla'), ('amber', 'Amber'), ('woody', 'Woody'), ('musk', 'Musk'), ('spicy', 'Spicy'), ('leather', 'Leather'), ('fruity', 'Fruity'), ('aquatic', 'Aquatic'), ('powdery', 'Powdery'), ('sweet', 'Sweet'), ('oriental', 'Oriental'), ('green', 'Green'), ('tobacco', 'Tobacco'), ('oud', 'Oud')], default='musk', max_length=30, verbose_name='Heart note'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='scent_3',
            field=models.CharField(choices=[('citrus', 'Citrus'), ('fresh', 'Fresh'), ('floral', 'Floral'), ('rose', 'Rose'), ('jasmine', 'Jasmine'), ('lavender', 'Lavender'), ('vanilla', 'Vanilla'), ('amber', 'Amber'), ('woody', 'Woody'), ('musk', 'Musk'), ('spicy', 'Spicy'), ('leather', 'Leather'), ('fruity', 'Fruity'), ('aquatic', 'Aquatic'), ('powdery', 'Powdery'), ('sweet', 'Sweet'), ('oriental', 'Oriental'), ('green', 'Green'), ('tobacco', 'Tobacco'), ('oud', 'Oud')], default='amber', max_length=30, verbose_name='Base note'),
        ),
    ]
