services:
  - type: web
    name: notematch
    env: python
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py repair_live_db && python manage.py seed_survey && python manage.py collectstatic --noinput
    startCommand: cd backend && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
